## Learning Git R Project

This project is to serve as an example while I learn git at a deeper level. 

I will be study along with Happy Git and GitHub for the useR https://happygitwithr.com

The first 2 sections (Chapter 1-19) are a little too basic for me. 



### git diff

I've just made these changes to the markdown: adding the git diff heading, and writing this sentence. I haven't staged or committed this yet. Now I'll run `git diff`. It shows the changes. Once I stage this changed file, git diff will again show no changes.

To view differences between what is in the staging and what is already committed, enter `git diff --staged`. `git diff --cached` is an alias for `git diff --staged`.

The `-w` flag will tell `git diff` to ignore whitespace changes.

`git diff` can also show the differences between two different commits.
To view a log of previous commits, use `git log`. Use the first 7 digits of the hash. To compare the commits: `git diff <commit1> <commit2>`

`git diff` can also compare two files with the --no-index flag. `git diff --no-index <file1> <file2>`. This will work with files even outside of the git directory.

By default, `git diff` shows the line-by-line difference, even if only a single character is changed. To display these smaller differences only, use the --word-diff flag: `git diff --word-diff`.

For a summary of the difference, use `git diff --stat`.



### git log
`git log` shows a history of commits. A few useful flags:
`git log --oneline`: condenses the output to one line per commi
`git log --graph` adds a simple node-edge graph to show relationship between commits, branches, and merges
`git log --parents` shows the parentc commit for each new commit
`git log --decorate` provides branch and tag info

Add these all together for a useful output
`git log --oneline --graph --decorate --parents`

Probly useful to give that an alias



### Aliases with git
To create an alias with git's built in system, change use `git config`. The `--global` flag makes this apply to the user and not just the curret project.: `git config --global`

Then to creat the alias add `alias.<nam>e <command>`

For example, to alias the useful git log with 4 options above:

`git config --global alias.logops "log --oneline --graph --decorate --parents"`
 Note for commands with more than one word, we need to wrap it in quotes.

With any alias, you can still add additional flags after passing the alias. 

To see the aliases in the git config file, print the file which is in the home directory:
`cat ~/.gitconfig`

To remove an alias, use the `--unset` flag:
`git config --global --unset alias.<name>`

This way of setting aliases within git is still a little cumbersome. After all, you have to type out git first this the alias. The other, more common way, of using aliases with the command line is to set them up in the shell (zsh, bash etc)

For the zsh shell, you can set aliases in the `~/.zshrhc` file, although more advanced shell configurations will use that file to call others files, including a `aliases.zsh` file that contains only shell aliases.

After editing `~/.zshrhc` you will need to source the file for it to update the configuration.: `source ~/.zshrc` (this is another useful one to shortcut).


### git config
While we're on the topic of `git config`, there are a few other global configuration options i need to set. One is my user info (name and email) which is currently defaulting to the system user name.

`git config --global user.name "FIRST LAST"`
`git config --global user.email "address"

Of course, you can also edit this in vim:
`vi ~/.gitignore`

But if you mess up and make a typo or do something nonsensical to git, then none of your git commands will execute. They will display fatal and declare which line of the config file has an error. 

### git branch
Making a new branch is easy enough: `git branch <name>.` Another common approach is to create the branch and checkout the branch in one line. `git checkout -b <name>`. checkout means switching to that branch. 

Managing branches in an orderly and coordinated way is a bit more difficult. There are several strategies
1. Git Flow
- Development occurs on the dev branch. Before deploying to the main branch, a release branch is made for testing and debugging. Hotfix branches can also be used to quickly fix issues with the main branch. In this system, the dev branch can go many commits before it is merged with the main branch. 


### git worktree
Where branching requires you to commit existing changes, sometimes that is not desirable but you still need to switch to a new branch to handle something else. That is where `git worktree` comes in. 
 
### git prune


### fast forward





